### ISSUE TITLE
Chore: Reduce `items` queries

### ISSUE THREAD

**Issue by SimonLab** [dwyl/mvp#131]
Now that the items are filtered on the view side using the `filter_items` function:
`<%= for item <- filter_items(@items, @filter) do %>`

We don't have to get the items when the filter change:
```elixir
  def handle_params(params, _uri, socket) do
    person_id = get_person_id(socket.assigns)
    items = Item.items_with_timers(person_id)
    filter = params["filter_by"] || socket.assigns.filter

    {:noreply, assign(socket, items: items, filter: filter)}
  end
```

become
```elixir
  def handle_params(params, _uri, socket) do
    filter = params["filter_by"] || socket.assigns.filter

    {:noreply, assign(socket, filter: filter)}
  end
```

We just need to add back the items in the `mount` function.
When an item is added, edited or removed the `handle_info` with the `update` message will make sure the `assigns.items` is up to date:

```elixir
  def handle_info(%{event: "update", payload: %{items: _items}}, socket) do
    person_id = get_person_id(socket.assigns)
    items = Item.items_with_timers(person_id)

    {:noreply, assign(socket, items: items)}
  end
```

**Comment by nelsonic** [comment]
Good call. Thanks for opening this issue and picking it up to simplify the code. 👌

**Comment by SimonLab** [comment]
#132 merged and deployed
