### ISSUE TITLE
Update `get_person_id`

### ISSUE THREAD

**Issue by SimonLab** [dwyl/mvp#134]
The `if/else` statement is bothering me in:
```elixir
  defp get_person_id(assigns) do
    if Map.has_key?(assigns, :person) do
      assigns.person.id
    else
      0
    end
  end
```

We can instead use:

```elixir
defp get_person_id(assigns), do: assigns[:person][:id] || 0
```
If `assings.person` is not defined then `assigns[:person][:id]` returns `nil`

I find this easier to read

**Comment by nelsonic** [comment]
Agreed. Much cleaner. Thanks.
