### ISSUE TITLE
Cannot import Phoenix.LiveView.assign_new/3

### ISSUE THREAD

**Issue by SimonLab** [dwyl/mvp#153]
[LiveView 0.18](https://hexdocs.pm/phoenix_live_view/changelog.html#0-18-0-2022-09-20) removed the `assign_new` function.
I can see there is one in [Phoenix.Component](https://hexdocs.pm/phoenix_live_view/Phoenix.Component.html#assign_new/3) but I need to read the doc and make sure it is the same.

Currently my [PR](https://github.com/dwyl/mvp/actions/runs/3104454632/jobs/5028951033)  is failing due to this issue

**Comment by nelsonic** [comment]
Seeing the same issue over in https://github.com/dwyl/auth_plug/pull/91 ... thanks for the reminder of solution. 👌
