### ISSUE TITLE
Setup formatter for .heex files

### ISSUE THREAD

**Issue by SimonLab** [dwyl/mvp#155]
The main template file (https://github.com/dwyl/mvp/blob/main/lib/app_web/live/app_live.html.heex) start to be difficult to read/navigate.
My neovim doesn't add highlight and the code is not automatically formatted on save.

I'm going to have a look at updating my editor to see if I can have the highlight and formatter working, this should help us to create the UI more easily and quickly

**Comment by nelsonic** [comment]
@SimonLab Good plan. Thanks for opening this issue and tackling. 👌

**Comment by SimonLab** [comment]
The formatter has been added.
The next version of pheonix (1.7) adds it by default
