### ISSUE TITLE
BUG: Timer has stopped counting ... 🤷‍♂️ 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/mvp#167]
@SimonLab don't know if you noticed, but the timers have stopped counting on the MVP: https://mvp.fly.dev
![image](https://user-images.githubusercontent.com/194400/194255186-461ed4bb-fb19-42ab-84ad-a089ff1f6dd4.png)

Please investigate when you can or ping me and I will dig into it. 🙏

**Comment by SimonLab** [comment]
It is working for me:
![image](https://user-images.githubusercontent.com/6057298/194257108-c40f4632-e27f-4134-9865-c351d994bdca.png)

Could it be an issue with your internet or js on your browser? Or maybe the fly app version on your side is not running properly?

**Comment by SimonLab** [comment]
The only thing I see on with `flyctl logs` is:
![image](https://user-images.githubusercontent.com/6057298/194258971-6dca8430-c14f-402d-8f31-043b844214ac.png)

Might be worth deleting any cookies/session on your browser if any and try again

**Comment by nelsonic** [comment]
This is very strange. It doesn't work in *any* browser on my Mac or iPhone but for some reason still works on the Windows box I use for CAD ... 🤦‍♂️ 

I've tried resetting my web browser to factory and still nothing. very strange. going to try restarting my computer after standup.

**Comment by nelsonic** [comment]
Restarted my Mac and it appears to be working. 👌 
Sorry for this.
