### ISSUE TITLE
BUG: Edit Profile Wall Before Being Allowed to Use the App

### ISSUE THREAD

**Issue by nelsonic** [dwyl/mvp#172]
Trying to run the `items-list` branch of the **`MVP`** on `localhost` ...
Ran:

```sh
git pull
git checkout items-list
mix deps.get
mix ecto.reset
mix s
```

Opened web browser and get this page blocking me from using the App: http://localhost:4000/profile/0/edit
![image](https://user-images.githubusercontent.com/194400/194943856-02ba61bc-f0a9-45db-969c-6aba3e1ff0f4.png)

This is an undocumented "feature" that is actually a _major_ UX antipattern. 😢 
Putting this kind of road-block in front of a new `person` using the `App` for the _first_ time is a recipe for _immediate_ dropout/bounce. This must be removed immediately. 

Never force a new person to perform an arbitrary administrative action they have no clue about 
***`before`*** _allowing_ them to view and interact with the application. Ever. 
This is the _definition_ of [wasting people's time](https://github.com/dwyl/start-here/blob/main/manifesto.md#your-time-should-never-be-wasted). 

Apologies if this comes across as "harsh" or "criticism". 
I just feel _very_ strongly about UX and there is _way_ too much poor UX out there.
This is _worse_ than those awful GDPR-lipservice-compliance cookie popups/banners we see everywhere
because it won't even allow me to dismiss it!

![image](https://user-images.githubusercontent.com/194400/194944923-1afc4739-4fe2-496a-9247-ffdc048bb90e.png)

Obviously "Name can't be blank" ... but we don't _WANT_ to capture a name for an anonymous visitor.
We want them to be able to take a "tour" of the MVP _without_ any friction.
We _must_ avoid it at all costs.

**Comment by nelsonic** [comment]
Wow. If I attempt to use the `Login` button it keeps redirecting me to this infernal "Edit Profile" page.

https://user-images.githubusercontent.com/194400/194945754-213521ee-0f1c-48cb-9841-7f2b4bbe9c1d.mov

This is _horrible_. 😭

**Comment by nelsonic** [comment]
Why do we _need_ a `Profile` ...? 🤷‍♂️ 

https://github.com/dwyl/mvp/blob/7d05242ed1b2443c147cfbaac477eae3b3a5e827/lib/app_web/templates/profile/edit.html.heex

Sorry if I'm missing something, but I don't remember this requirement. 🔍 
What feature is this in aid of? 💭

**Comment by SimonLab** [comment]
> What feature is this in aid of? thought_balloon

I've added the `people` table to the application contains the `person_id` (the same received from `auth`) and a `name`
I need the name to be defined when the user want to share lists of items.

When listing the groups I've created, I have the `member` link:
![image](https://user-images.githubusercontent.com/6057298/195025955-7f83d5f5-2cda-4631-aa8c-5505a31f3fa6.png)

From there I can add a new person to the group using the unique name field to find this person:
![image](https://user-images.githubusercontent.com/6057298/195026097-502ef981-8f25-474c-b67e-e325f8f26dd6.png)

It might not have been the best place to redirect the user on the `items` page and instead only do this check when the user attempt to access the `member` page.

Again this is only one solution to add members to a group using the `name`

**Comment by nelsonic** [comment]
@SimonLab we very deliberately _removed_ `people` from the **`MVP`** ✂️ 
because we didn't _need_ to store the data. remember: https://github.com/dwyl/mvp/issues/118 ? ⌛
Since we reached that conclusion, I've not looked back. It's the _right_ thing to do. 👌 

I know it can seem like extra effort to separate `auth`, `people`, etc. into a distinct app that handles all [**`PII`**](https://en.wikipedia.org/wiki/Personal_data) ... 👤 
But it's a legal requirement to **take _extra_ care of personal data**. 👮‍♂️ 
If we _eliminate_ all **PII _storage_** in the **`MVP`/`App`** we avoid potential data breach issues. 🔐 

Simplifying the [**`ERD`**](https://github.com/dwyl/mvp/issues/118#issuecomment-1206386753) of the **`MVP`/`App`** by eliminating superfluous tables is a huge win. 🎉 
Even in the _short_-term if we want to have people contributing to the dwyl **`App`**, 📱 
we must do _everything_ we can to streamline the `DevEx`. 👩‍💻 🚀 
Hence my _obsession_ with **_ONE_ Environment Variable<sup>TM</sup>** to add [**`auth_plug`**](https://github.com/dwyl/auth_plug) to a project. 1️⃣ 
  
Yes, on `localhost` someone running/contributing to our **`App`** will only have access their **_own_ data**, 
i.e: the Google/GitHub/Email account they have access to ... So there's technically no issue with them storing it. ✅ 
But the principal remains: if we _always_ protect personal data and only store the bare minimum in _one_ place fully encrypted, we are setting ourselves up for long-term success and legal compliance. 💭 
I wish _all_ Apps did this! 


Now, back to this undocumented feature (BUG) ... We need to re-think it as **`P1`**.

**Comment by nelsonic** [comment]
Current **`ERD`** on `main` branch:
![image](https://user-images.githubusercontent.com/194400/195434654-76739589-3481-4808-9c40-4f28887fa1b6.png)

**Comment by nelsonic** [comment]
Re-arranged for better layout without crossed lines:

![image](https://user-images.githubusercontent.com/194400/195436281-4a4acb0d-9168-4512-9398-a73450d08032.png)

I actually think this ERD is very easy to understand. 👍 
I just feel that if we don't ***need*** the `people` table, we should avoid it: #118 ✂️

**Comment by nelsonic** [comment]
Re-arranged for better layout without crossed lines:

![image](https://user-images.githubusercontent.com/194400/195436281-4a4acb0d-9168-4512-9398-a73450d08032.png)

I actually think this ERD is very easy to understand. 👍 
I just feel that if we don't ***need*** the `people` table, we should avoid it: #118 ✂️
