### ISSUE TITLE
404 Error after attempting to authenticate through Github

### ISSUE THREAD

**Issue by LuchoTurtle** [dwyl/mvp#174]
I was trying to authenticate with Github this morning so I could add a task to myself and I got a 404 Not Found error.
<img width="1776" alt="down" src="https://user-images.githubusercontent.com/17494745/195300481-8748f623-3186-4532-9085-ac948a95d5f9.png">

After refreshing the website, it now seems the WHOLE web app is down. No URL paths apparently work 😦

**Comment by nelsonic** [comment]
@LuchoTurtle thank you very much for opening this issue. 🔥 
Please try this again in **`Safari`** on your **Mac** so that we can isolate the variables. 🙏 
You appear to have a few Chrome plugins installed we need to test without any "interference". 💻 
Report back with your progress. 👍

**Comment by nelsonic** [comment]
@LuchoTurtle thank you for updating the title and re-opening the issue. ♻️ 
We need to investigate this ASAP. Should I bring my laptop to your desk and we **`pair`** on debugging this? 💻 🔥

**Comment by LuchoTurtle** [comment]
Turns out it's not plugin-related. You can replicate my issue by:

1. Going to [mvp.fly.dev](https://mvp.fly.dev).
2. Logging in through Github
<img width="1840" alt="Screenshot 2022-10-12 at 10 33 38" src="https://user-images.githubusercontent.com/17494745/195306893-7a2fbd78-7b58-46ae-8ec5-7b9de7518461.png">
3. After logging in, the 404 error props up. 
<img width="1840" alt="Screenshot 2022-10-12 at 10 34 30" src="https://user-images.githubusercontent.com/17494745/195307129-aec80886-b94f-4cc0-bd16-b52afc91780f.png">
4. Now the whole website is down 😦 .
<img width="1840" alt="Screenshot 2022-10-12 at 10 35 12" src="https://user-images.githubusercontent.com/17494745/195307338-e36df5a8-782d-4e72-b67c-4fff4c866f99.png">

This happens in Safari as well. You can replicate this with an incognito window on Chrome.

**Comment by LuchoTurtle** [comment]
Sure let's do it @nelsonic

**Comment by nelsonic** [comment]
Noted. Just opening an issue for Stephany to work on in the next hour. will be right with you. Hopefully you have something else e.g: https://github.com/dwyl/phoenix-chat-example/issues/54 you can look at in the mean time. 🤞

**Comment by nelsonic** [comment]
Let's take a look at this now. 🧑‍💻 ⏳ 🔥

**Comment by LuchoTurtle** [comment]
Just tried with Google Auth and got the following error:

<img width="1225" alt="image" src="https://user-images.githubusercontent.com/17494745/195330125-c69759d5-94d6-4dff-b3e4-dd051c467e40.png">

Even _worse_ than the `404` ... 🤦

**Comment by nelsonic** [comment]
That's super lame. I cannot replicate it in any browser on my machine. 

> But I do see this "Edit Profile" wall:
> ![image](https://user-images.githubusercontent.com/194400/195351606-d88937e1-18d1-4f59-942e-467063d1d8ce.png)
> Which is another issue I want to address _immediately_ after this one: #172 

@LuchoTurtle if you have time now, I could open the Fly.io Logs for both the **`MVP`** and **`auth`** and we can attempt to debug this. 🧑‍💻

**Comment by nelsonic** [comment]
OK, I'm able to replicate the `404` in a **`private` `Safari`** session: ⛔ 

![image](https://user-images.githubusercontent.com/194400/195375841-a7147fad-c0cf-41b6-bbac-2be72e333ac0.png)

It appears that the `auth` redirect is no longer working 🤷‍♂️ 
Or ... it works for my (non incognito session) but not in this **`private`** window. 🦹‍♂️

**Comment by nelsonic** [comment]
According to the logs for the **`MVP`** App: https://fly.io/apps/mvp/monitoring
![image](https://user-images.githubusercontent.com/194400/195376538-e28757aa-c0cb-40c7-89fa-a0d86c08db26.png)

The failure is:

```sh
SELECT p0."person_id", p0."name", p0."inserted_at", p0."updated_at" FROM "people" AS p0 WHERE (p0."person_id" = $1) [142]

14:52:59.996 request_id=Fx1Z_OpPI33afeIAACRx [debug] Converted error Ecto.NoResultsError to 404 response
```

Looking up the `person` is what is breaking this request.
The person doesn't exist and therefore the session fails.

Let's fix this. 🛠️

**Comment by nelsonic** [comment]
To be clear: the **`MVP`** is still _working_ for me in my main window: 

![image](https://user-images.githubusercontent.com/194400/195395573-0a36f45a-cba1-4e5e-b776-602c1d66644d.png)

So I had to go out of my way to see the issue. But it's definitely there for **`new`** people trying to use the **`MVP`**.

**Comment by SimonLab** [comment]
It looks like https://github.com/dwyl/mvp/issues/174#issuecomment-1276316668 is also the issue I've spotted https://github.com/dwyl/mvp/issues/168
I've added a fix on the `list` PR https://github.com/dwyl/mvp/pull/165#discussion_r991913164
I can extract this code to a new PR while list is being worked on.
In the future, I don't think we'll need this as the `people` table might be removed

**Comment by nelsonic** [comment]
@LuchoTurtle thank you for confirming you are able to login using GitHub. 🎉 
Please proceed to: #140 🙏
