### ISSUE TITLE
Format templates (heex files)

### ISSUE THREAD

**Issue by SimonLab** [dwyl/mvp#183]
LiveView 0.18 provide a formatter plugin for the `heex` files: [Phoenix.LiveView.HTMLFormatter](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.HTMLFormatter.html)

I think it requires Elixir 1.3 to be able to work and we need to update the `.formatter` file as described in the [setup section](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.HTMLFormatter.html#module-setup)

I'm also tempted to add `mix format --check-formatted` action on the Github actions to make sure PRs are formatted, this shouldn't be too annoying as I think most of editors have the option to format the code when a file is saved.

**Comment by nelsonic** [comment]
@SimonLab thanks for opening this. 👌 
Reviewing your PR #184 now 👀

**Comment by SimonLab** [comment]
I'm not sure if the future new version of Phoenix will add the heex formatter automatically in the `.formatter` file.
I'll open an issue on the liveview-chat-example to remind me to add the step in the Readme :+1:

**Comment by nelsonic** [comment]
Yeah, will make perfect sense for future `Phoenix` to include this out-of-the-box. 👌

**Comment by SimonLab** [comment]
Arf, the main branch failed and didn't deployed the last PR as:
![image](https://user-images.githubusercontent.com/6057298/196901270-260efb4e-4aa9-49d7-8491-e6bf195ec753.png)

So the liveView formatter module is still not found, however it looks like the `router` file is not formatted, I'll have a look at what could be wrong. However If this step becomes annoying with the Github CI, I think we could remove it for now

**Comment by SimonLab** [comment]
running `mix compile` before `mix format` seems to be the solution to be able to use the Phoenix.LiveView.Formatter plugin.
see https://github.com/elixir-lang/elixir/issues/11915#issuecomment-1233077725

**Comment by SimonLab** [comment]
Updating the version of elixir to 1.14 seems to work for running `mix format` on Github CI.
It will automatically run `mix compile` before running `mix format`

I'm looking now at updating the Dockerfile to make sure the application can be deployed on Fly using the correct version.
We can see which versions to select for Elixir OTP and debian at https://hub.docker.com/r/hexpm/elixir/tags?page=1&name=slim

I've seen a couple of posts already on the Fly community where people had issue deploying with Elixir 1.14: https://community.fly.io/t/no-love-with-first-deployment-attempt-of-phoenix-app/7358/2

Hopfully selected the correct Debian and elixir/OTP version on the Dockerfile should also work for us.

**Comment by nelsonic** [comment]
Thanks for looking into this @SimonLab 👌

**Comment by SimonLab** [comment]
Just to make sure the application has been deployed with the correct versions:
- connect to the fly application with: `fly ssh console`
- then run an iex session with `/app/bin/app remote`
![image](https://user-images.githubusercontent.com/6057298/197041840-e869a229-9e80-4aa9-b39f-132d9b6e1443.png)

see [IEx Shell Into Your Running App](https://fly.io/docs/elixir/getting-started/#iex-shell-into-your-running-app)
