### ISSUE TITLE
Use Select input for tags

### ISSUE THREAD

**Issue by SimonLab** [dwyl/mvp#201]
Now that the select input example is ready: https://github.com/dwyl/learn-alpine.js/pull/18

I'm trying to add it for adding tags:

![image](https://user-images.githubusercontent.com/6057298/201338328-5b6922d8-199f-4947-99eb-d64b46dc4fd5.png)

I think I need to review the existing classes on the other element of the page to make sure we have the correct structure to add the select input without too many issues.

**Comment by SimonLab** [comment]
At the moment tags are created directly with the input text. However adding the new select/dropdown doesnt' allow you to create on the fly new tags.

So we need to add a "new" button on the `/tags` endpoint to create new ones:
![image](https://user-images.githubusercontent.com/6057298/201341783-6b978c41-1ff1-4730-b937-1025d6773197.png)

- [ ] Add new tag button

**Comment by nelsonic** [comment]
These two screenshots are a reminder that our MVP needs some major UI TLC. 💭

**Comment by SimonLab** [comment]
Display list of tags:
![image](https://user-images.githubusercontent.com/6057298/203653240-c1c34463-8ea6-46d3-9874-4af5fb132564.png)


Display selected tags:
![image](https://user-images.githubusercontent.com/6057298/203653186-7a792785-e596-4559-80a0-105a36de62ea.png)

Add "edit tags" link at the bottom of the list tags, useful when there aren't any tags:
![image](https://user-images.githubusercontent.com/6057298/203653366-c34750eb-f308-42c3-b6f9-790d3aeaa285.png)

The select input tags is working for the new item.
I want to see if I can change the code to a phoenix component that I can then reuse when editing the existing tasks

**Comment by nelsonic** [comment]
@SimonLab, @iteles, @LuchoTurtle, @Stephanymtr & @seaneady 👋 
Please let me know your thoughts on the following Tags Progressive UI/UX:

<img width="2708" alt="image" src="https://user-images.githubusercontent.com/194400/214719780-a6594ba8-ec9b-48cc-a20c-664d855b2e1b.png">

Direct link to Figma page: https://www.figma.com/file/WrpkKGJNYZbeCzMRDVtvQLbC/dwyl-app?node-id=246%3A2

**Comment by LuchoTurtle** [comment]
Having read through Level 1 and Level 2, I found it quite enlightening and found no issue with the logic behind each decision, given it's meant to onboard the user into the app in their first "trial".

My only question is on Level 2. When the person starts typing an issue, the rest of the page is hidden, focusing solely on the `save` button and `textfield`. However, what happens if the person decides he wants to cancel the action and go back? Is he meant to delete all of the text to "go back" and see the navigation buttons? Does he click away from the keyboard?

I find that either option has its pros and cons. The first can be time-consuming but it has a "clear path". However, in the latter scenario, the user might click away by mistake and lose all the progress writing the item.

**Comment by nelsonic** [comment]
@LuchoTurtle excellent question! 🎉 ❤️ 
This deserves it's own issue and a section in Figma for clarity. 👌 
Please open the issue here on `MVP` or on `App` and I will try my best to address it this morning. 🙏

**Comment by LuchoTurtle** [comment]
Created the issue https://github.com/dwyl/app/issues/299

**Comment by nelsonic** [comment]
@LuchoTurtle responded on the issue: https://github.com/dwyl/app/issues/299#issuecomment-1405283372 ✅ 
and in FIgma: https://www.figma.com/file/WrpkKGJNYZbeCzMRDVtvQLbC/dwyl-app?node-id=1512%3A4730

**Comment by nelsonic** [comment]
@SimonLab please share your thought on the tags UI/UX outlined above. ⬆️ https://github.com/dwyl/mvp/issues/201#issuecomment-1404389473

**Comment by SimonLab** [comment]
My current thought on progressive UI/UX for the app:
- https://github.com/dwyl/app/issues/305#issuecomment-1428218595
- https://github.com/dwyl/app/issues/305#issuecomment-1429353078

Otherewise a couple of question we need to test with the UI implementation in Flutter:

- Can we add the tag text field and the save button next to each other without making these two widgets too small or squished? I think I tried previously on the mobile view of the mvp and it was getting difficult to read the labels name especially if they are long. It might be fine with the right font size and widget widths with Flutter
![image](https://user-images.githubusercontent.com/6057298/218704101-3c59298f-38d3-4384-92b3-32d4f31e7a31.png)

- Having the selected tags above the input (text field widget) solve the issue of not seeing the tags you have selected when they are behind the dropdown. However I'm wondering if having the text field pushed down each time a new line of tags is added will be annoying for the person selected the tags. It might not, to be tested.
![image](https://user-images.githubusercontent.com/6057298/218704306-7df5c33b-94b1-44b9-ac26-05be66821052.png)

**Comment by nelsonic** [comment]
@SimonLab thanks for your feedback. 
Yes, it might be "tight" to have the save button and tags.
Fairly certain we will be getting rid of the "Save" button soon though.
So let's just focus on tags in `Flutter`. 👌
