### ISSUE TITLE
`mvp-db` ran out of memory and crashed 🤦‍♂️ 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/mvp#236]
<img width="1190" alt="image" src="https://user-images.githubusercontent.com/194400/207621080-69be849e-12d8-44af-b97a-57ffb9f44ec1.png">

```sh
Hello! Your “mvp-db” application hosted on Fly.io crashed because it ran out of memory. 
Adding more RAM to your application might help!

You should know that adding RAM does cost money. Not much, but some. 
Figure about $5/mo per extra GB. Our docs have complete pricing details: https://fly.io/docs/about/pricing

When you’re ready, add more RAM by running:

fly scale vm shared-cpu-1x --memory 1024 -a mvp-db

(from looking at your current app, this is our best guess as to how much memory you should try using)

Here’s the raw log message:

Out of memory: Killed process 16466 (postgres) total-vm:155564kB, 
anon-rss:1804kB, file-rss:0kB, shmem-rss:15344kB, 
UID:1000 pgtables:152kB oom_score_adj:0
```

We have 3 people using the `MVP`. ***Why*** is it running out of Memory?! 🤷‍♂️

**Comment by SimonLab** [comment]
I've opened the following PR https://github.com/dwyl/mvp/pull/234 which has attached the mvp-db Postgres cluster to the new "review" app. This might have be the origin of the issue. see also #235

**Comment by nelsonic** [comment]
https://fly.io/dashboard/dwyl-mvp
<img width="1402" alt="image" src="https://user-images.githubusercontent.com/194400/207633688-6b4722da-6810-40af-804a-cfe1bf35a135.png">

The DB ~~has~~had **`256MB`** of RAM: https://fly.io/apps/mvp-db

<img width="1583" alt="image" src="https://user-images.githubusercontent.com/194400/207633876-139219aa-3ca7-4f3a-9ba0-7b8b4453bc5e.png">

I've run:

```sh
fly scale vm shared-cpu-1x --memory 512 -a mvp-db
```

Got:

```sh
WARN app flag 'mvp-db' does not match app name in config file 'mvp'
? Continue using 'mvp-db' Yes
Scaled VM Type to
 shared-cpu-1x
      CPU Cores: 1
         Memory: 512 MB
```

Confirmed: https://fly.io/apps/mvp-db

<img width="1583" alt="image" src="https://user-images.githubusercontent.com/194400/207634555-6fade60c-b7c3-46d8-a177-44aa290dd9af.png">

Let's see if this happens again. 

Meanwhile I will review the PR so we can close the review apps that are sitting idle. 👍

**Comment by nelsonic** [comment]
This hasn't happened again recently. 👍 
Closing. ✅

**Comment by nelsonic** [comment]
![image](https://user-images.githubusercontent.com/194400/213408339-8611ea28-48fe-4c5f-928d-55e95472d622.png)
