### ISSUE TITLE
Lame: `<textarea>` `item.text` wiped by `LiveView` refreshing the page ...! 😢 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/mvp#247]
I was just writing some text in the `item.text` `<textarea>` and it was wiped by `LiveView` doing a refresh of the page. 🤦‍♂️ 
This is unacceptably poor UX! 😢 
My guess is that it was re-acquiring the socket connection ... 
but the blue loading/progress bar crossed the screen and my text was _gone_! 😭 
(yes, it wasn't a lot of text and I can easily re-type it, but that's not the point...!)

We _either_ need a way of caching the text and preventing page refresh 👨‍💻 
***or*** it's time to ditch `LiveView` and focus all our efforts on the offline-first `Flutter` version. 💭

**Comment by nelsonic** [comment]
The problem with MVPs: https://www.monkeyuser.com/2018/production-ready/

![image](https://user-images.githubusercontent.com/194400/210715450-d6ed8909-55fa-488c-984a-41249a15eabc.png)

If `LiveView` "owns" the `DOM` how do we intercept a page-refreshing update that wipes the `<textarea>` ? 🤷‍♂️

**Comment by nelsonic** [comment]
This just happened to me again.
I think it happens when you return to a window after a while (I last looked at this yesterday) and ***`while`*** you are typing the `channel` connection refreshes and it resets the `LiveView` page losing whatever you have typed.
Super duper lame. 😕 
This would happen to other people who keep the `MVP` open on their desktop e.g. in a tab in their browser and then return to it after a `while` ... ⏳ 
This is unacceptable UX that would cause me "as a `user`" to _immediately_ stop using this App. 👎 

@SimonLab / @LuchoTurtle from what you've read about LiveView, is there any way around this? 🤷‍♂️

**Comment by SimonLab** [comment]
> I think it happens when you return to a window after a while (I last looked at this yesterday) and while you are typing the channel connection refreshes and it resets the LiveView page losing whatever you have typed.

Yes

The textarea value is defined with:
https://github.com/dwyl/mvp/blob/85b5cab8b8d0ee6e717c702d637925c219871b99/lib/app_web/live/app_live.html.heex#L29

The `text_value` is created and updated with liveview, so if the socket connection is reset this value will be created again on mount:
https://github.com/dwyl/mvp/blob/85b5cab8b8d0ee6e717c702d637925c219871b99/lib/app_web/live/app_live.ex#L15-L35

I've added this value with the following commit https://github.com/dwyl/mvp/commit/8c6cd75094d89950185d0b12a061ce6ef031e43c

![image](https://user-images.githubusercontent.com/6057298/211301550-bf469e1a-3ced-499d-a2f7-8b548757b94f.png)

**Comment by SimonLab** [comment]
I'll have a look if I can remove the `text_value` from the textarea without breaking the tags. This should fix the socket reloading the page issue.

Otherwise to have this feature we need to have a cache system on the client, however I think it might be time consuming to implement and difficult to maintain, especially if we're going to use a rich text editor later on.

**Comment by nelsonic** [comment]
We need a _separate_ issue for proactively storing content on the device (and DB) for `items` that haven't been explicitly saved: https://github.com/dwyl/mvp/issues/253

**Comment by nelsonic** [comment]
This is working now on the `MVP`. ✅
