### ISSUE TITLE
Chore: Avoid creating Review Apps for @dependabot PRs

### ISSUE THREAD

**Issue by nelsonic** [dwyl/mvp#259]
Just noticed that review apps script runs on @dependabot PRs: https://github.com/dwyl/mvp/pull/257

![image](https://user-images.githubusercontent.com/194400/212034063-36396881-29cb-4063-beeb-0ceb3e856cd9.png)

There doesn't _appear_ to be any check for the branch name in:
https://github.com/dwyl/mvp/blob/main/.github/scripts/review-apps.sh

@SimonLab could you please confirm my understanding? 🙏 

The @dependabot PRs have `dependabot/` in the the branch name `dependabot/hex/petal_components-0.19.8` 
So we can easily detect them and avoid creating a Review App when one is not needed. 💭

**Comment by SimonLab** [comment]
- Check author of the PR:
https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#accessing-and-using-event-properties

![image](https://user-images.githubusercontent.com/6057298/212045980-a26faaff-58e9-454a-ae8f-017f4fa399e3.png)

- Run job only when condition is ok (using if):
https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution

![image](https://user-images.githubusercontent.com/6057298/212046237-c40542c4-a0f6-40b7-8f90-b873c351c54e.png)

**Comment by SimonLab** [comment]
#260 PR  should fix this issue.
Once merged we can check on the next Dependabot PRs if the github action is skipped.

**Comment by nelsonic** [comment]
@SimonLab thanks for addressing this so swiftly. 👍

**Comment by SimonLab** [comment]
New Dependabot PR:
![image](https://user-images.githubusercontent.com/6057298/212285593-1ba59a26-3363-48de-b11b-ef54a8d39519.png)

The review app action is skipped

**Comment by nelsonic** [comment]
Thanks again @SimonLab 👍
