### ISSUE TITLE
Stats not updating correctly and page not loading

### ISSUE THREAD

**Issue by LuchoTurtle** [dwyl/mvp#261]
It seems an error occurs when mounting the page.

![image](https://user-images.githubusercontent.com/194400/212057435-773d58fd-cebc-4c4c-8702-732797467702.png)

This is because of the change to the SQL query expression, introduced in https://github.com/dwyl/mvp/commit/dfc9891943d596ecbd66448df2b6b0a35bf164b5.

```
(Postgrex.Error) ERROR 42702 (ambiguous_column) column reference "person_id" is ambiguous
```

https://github.com/dwyl/mvp/commit/72d9fb42342ec575aef5eca2d37d950da145482f also introduced a bug where only `timers` are updated and not `items`.

**Comment by nelsonic** [comment]
https://mvp.fly.dev/stats
![image](https://user-images.githubusercontent.com/194400/212190340-3362fbb8-0044-4597-b90c-eab22e4e224e.png)

Appears to be working. 👍 
Thanks again @LuchoTurtle
