### ISSUE TITLE
Remove `people` table from database on Fly.io

### ISSUE THREAD

**Issue by SimonLab** [dwyl/mvp#285]
#281 has been fixed by removing the foreign key `items_people_id`.
However the `people` table still exists on the database.

- [x]  Check all the foreign keys are removed
- [x] Drop the people table

**Comment by SimonLab** [comment]
The `tags` table still has a foreign key index to the `people` table:
![image](https://user-images.githubusercontent.com/6057298/214609772-d6ddaa8b-93b6-4cf0-b560-248f92f8280e.png)

Running: `alter table tags drop constraint tags_person_id_fkey;` to remove the index. We should now be able to drop the people table with `drop table people;`

Listing the tables:
![image](https://user-images.githubusercontent.com/6057298/214611842-374f3d39-cc74-4a61-8cc7-52acc24a26ed.png)

@nelsonic @LuchoTurtle let me know if you have any issues with the mvp but I think now the database reflect the migrations files we have on the project.

**Comment by nelsonic** [comment]
@SimonLab go for it. thanks. 👍

**Comment by SimonLab** [comment]
No errors reported closing for now
