### ISSUE TITLE
Textarea reduces size automatically after a few seconds

### ISSUE THREAD

**Issue by SimonLab** [dwyl/mvp#305]
[new-line-textarea.webm](https://user-images.githubusercontent.com/6057298/218695734-656fe346-2d68-4a3f-8e32-8edd748b67d1.webm)

Do you have the same issue on your side?

**Comment by LuchoTurtle** [comment]
I get the same behaviour.
I think this is a behaviour introduced by `Alpine.js`. 
Check https://www.youtube.com/watch?v=z7130uJ3H7w&ab_channel=Codecourse 😎

**Comment by SimonLab** [comment]
Thanks for confirming this bug @LuchoTurtle I'll have a look what trigger the resize.

**Comment by LuchoTurtle** [comment]
<img width="1398" alt="image" src="https://user-images.githubusercontent.com/17494745/218726650-a1bad2cb-a726-4fea-96e6-32bee16ae1bf.png">

My guess is the resize function that is added to the `x-data` attribute :)

**Comment by SimonLab** [comment]
It is indeed linked to the `resize` function:
https://github.com/dwyl/mvp/blob/a1269f53bf177c2acb2d07f350eba110a9e73e4c/lib/app_web/live/app_live.html.heex#L23-L27

More specifically this bug is linked to the `debounce` function called after 2 seconds:
https://github.com/dwyl/mvp/blob/a1269f53bf177c2acb2d07f350eba110a9e73e4c/lib/app_web/live/app_live.html.heex#L19-L20

This will trigger the liveView `validate` event which is used to the save the `draft` text item:
https://github.com/dwyl/mvp/blob/a1269f53bf177c2acb2d07f350eba110a9e73e4c/lib/app_web/live/app_live.ex#L41-L47

So the draft is saved and the text value send back to the html via the socket and liveview.
However the `resize` function is not called (or not properly called) at this moment and the size of the textarea is wrong.

I'm trying to understand if it's an issue of compatibility between liveview and alpine.js or if I can add/remove some code to make it work.

**Comment by SimonLab** [comment]
After adding some `console.log`, I know the `x:init` function is properly called after liveView has updated the text draft:
https://github.com/dwyl/mvp/blob/a1269f53bf177c2acb2d07f350eba110a9e73e4c/lib/app_web/live/app_live.html.heex#L29-L32

The issue is that `resize` is not properly called and it should be `resize()`!

**Comment by nelsonic** [comment]
@SimonLab you've marked this as `awaiting-reveiw` but it's still assigned to you. 💭 
If you would like someone `else` to review it, please assign. 🙏
