### ISSUE TITLE
Clicking enter when in the tag field should add the tag to the timer

### ISSUE THREAD

**Issue by iteles** [dwyl/mvp#308]
Clicking enter when in the tag field saves the whole timer without the tag, rather than adding the tag to the task.

This was a case of **unexpected UX** for me which felt like a bug (but obviously isn't).

To recreate:
1. Type out your issue in the Capture box
2. Start typing out a tag in the tag field
<img width="693" alt="image" src="https://user-images.githubusercontent.com/4185328/219381705-9442d3d6-e73e-474d-8f82-a2ab1a245bd0.png">
3. Once the tag appears, press enter and you get a saved task with _no_ tags:
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/4185328/219383279-2e7eba76-7df9-404e-b9ee-9695ed373b47.png">

## Desired behaviour
This is what I would suggest is the desired behaviour based on familiar UX:

As a user of the app who is in a hurry and uses my keyboard for faster navigation,
I would like to be able to add tags to a task by typing the first few letters of a tag and being able to press enter to add the tag when the tag appears
So that I can speed up the process of adding one or multiple tags.

1. Start typing in the tag field
2. List of tags reduces to show only the newly relevant tags based on what has been typed [already happens :heart:]
3. The top item of the reduced list of tags is automatically selected
4. When enter is pressed _whilst in the tags field_ (as opposed to the main capture field), this top selected tag is saved as a tag on the task currently being written up) AND the tags field is automatically wiped

**Comment by panoramix360** [comment]
hey! I just crossed the repo `dwyl/start-here` and I found this project :)

It's currently being developed/maintained? (with my research I believe that it is)

Can I try to tackle this issue or is someone already doing it?

**Comment by panoramix360** [comment]
Created this [PR](https://github.com/dwyl/mvp/pull/389) to be reviewed related to this issue!

**Comment by panoramix360** [comment]
I believe we can close this issue :D

**Comment by nelsonic** [comment]
Thanks again @panoramix360. 👍
