### ISSUE TITLE
chore: MVP on Fly.io is suspended

### ISSUE THREAD

**Issue by LuchoTurtle** [dwyl/mvp#385]
The `mvp` app on https://fly.io/apps/mvp is currently suspended, which doesn't allow us to deploy the app after merging PRs - e.g. https://github.com/dwyl/mvp/actions/runs/5180194553/jobs/9334193999

<img width="1303" alt="image" src="https://github.com/dwyl/mvp/assets/17494745/9c3ac3fc-031e-4f9b-a425-623959678029">

Is this intentional? Is this related to the `Apps v1 to v2` migration?

**Comment by LuchoTurtle** [comment]
If we're migrating to a V2 app, we should be aware that new apps **have both automatic starting and automatic stopping enabled by default**.

https://community.fly.io/t/automatically-starting-stopping-apps-v2-instances/12342

**Comment by nelsonic** [comment]
Updated via CLI: `fly migrate-to-v2` appears to have worked: https://fly.io/apps/mvp

<img width="1195" alt="image" src="https://github.com/dwyl/mvp/assets/194400/7d422b94-5111-45d4-859d-a644e9063484">

PR with update to `fly.toml`: https://github.com/dwyl/mvp/pull/386

App is still working as expected: https://mvp.fly.dev
![image](https://github.com/dwyl/mvp/assets/194400/21df2f1c-0574-4d34-ad35-8fee74d73468)

**Comment by nelsonic** [comment]
This is no longer an issue. Thanks again for opening @LuchoTurtle 👌
