### ISSUE TITLE
chore: `useful` 1.12 upgrade introduced `Plug.Upload.__struct__/0 is undefined` error

### ISSUE THREAD

**Issue by LuchoTurtle** [dwyl/mvp#406]
We're getting this error when compiling the app.

```
Error: ** (CompileError) lib/useful.ex:24: Plug.Upload.__struct__/0 is undefined, cannot expand struct Plug.Upload. Make sure the struct name is correct. If the struct name exists and is correct but it still cannot be found, you likely have cyclic module usage in your code

```

This is due to a release made from https://github.com/dwyl/useful 4 days ago. This is causing the `Review App` job to crash, subsequently not allowing other checks to be made.

https://github.com/dwyl/mvp/actions/runs/5860010329?pr=405

**Comment by LuchoTurtle** [comment]
@nelsonic because this was merged 4 days ago https://github.com/dwyl/useful/commit/f112aad51153fa443b1342b0fe54454e7adf03b9, perhaps you may have any insights on this issue and on why it's happening? It should actually work.

https://github.com/dwyl/useful/blob/35278cfb0c697cab555becfcc27ccf46731e61ee/lib/useful.ex#L24

**Comment by nelsonic** [comment]
This is very peculiar. Because Plug is available in Phoenix. 💭🤷‍♂️

**Comment by nelsonic** [comment]
https://github.com/dwyl/mvp/actions/runs/5859641198/job/15887393605#step:4:1320
![image](https://github.com/dwyl/mvp/assets/194400/ec57d630-532f-4446-a921-760b54d07aca)

**Comment by nelsonic** [comment]
PR: https://github.com/dwyl/useful/pull/53 fixes this issue upstream. ✅
